apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "draino.fullname" . }}
  labels:
    {{- include "draino.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "draino.fullname" . }}
  labels:
    {{- include "draino.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "draino.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "draino.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "draino.fullname" . }}-node-read
  labels:
    {{- include "draino.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "draino.fullname" . }}-node-read
  labels:
    {{- include "draino.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "draino.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "draino.fullname" . }}-node-read
